apiVersion: v1
kind: ResourceQuota
metadata:
  name: hermes-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "2"
    services: "2"
    secrets: "5"
    configmaps: "5"
    pods: "3"
